title: Hello, world! I'm Mohit Meshram
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/info" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Mohit Meshram # add your name
author-img: IMG_1740.jpg # add your photo
about-author: I am a software engineer with skills focused on Python Development, Cloud and 
  Data Engineering. I have solid experience of working on a range of technologies and projects meeting requirements 
  such as automation, big data, API development, analytics and DevOps.   # add description
social-github: mohit-meshram # add your Github handle
social-linkedin: www.linkedin.com/in/mohit-meshram
social-email: meshmht@gmail.com

# Build Settings
markdown: kramdown
remote_theme: mohit-meshram/my_github_page_theme
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
